/// Keys of the interface strings: flat and dotted, the same in every language
enum TextKey: String, CaseIterable {
    case menuAppAbout = "menu.app.about"
    case menuAppHide = "menu.app.hide"
    case menuAppHideOthers = "menu.app.hideOthers"
    case menuAppShowAll = "menu.app.showAll"
    case menuAppQuit = "menu.app.quit"
    case menuFile = "menu.file"
    case menuFileDisconnect = "menu.file.disconnect"
    case menuFileClose = "menu.file.close"
    case menuWindow = "menu.window"
    case menuWindowMinimize = "menu.window.minimize"
    case menuWindowFullScreen = "menu.window.fullScreen"
    case connectionHostLabel = "connection.host.label"
    case connectionHostPlaceholder = "connection.host.placeholder"
    case connectionUserLabel = "connection.user.label"
    case connectionUserPlaceholder = "connection.user.placeholder"
    case connectionPasswordLabel = "connection.password.label"
    case connectionActionConnect = "connection.action.connect"
    case connectionActionDisconnect = "connection.action.disconnect"
    case connectionStatusInvalidHost = "connection.status.invalidHost"
    case connectionStatusConnecting = "connection.status.connecting"
    case connectionStatusConnected = "connection.status.connected"
    case connectionStatusDisconnected = "connection.status.disconnected"
    case connectionStatusStartFailed = "connection.status.startFailed"
    case connectionStatusNoMetal = "connection.status.noMetal"
    case connectionErrorHostNotFound = "connection.error.hostNotFound"
    case connectionErrorUnreachable = "connection.error.unreachable"
    case connectionErrorConnectionLost = "connection.error.connectionLost"
    case connectionErrorSecurityFailed = "connection.error.securityFailed"
    case connectionErrorCertificateRejected = "connection.error.certificateRejected"
    case connectionErrorAuthentication = "connection.error.authentication"
    case connectionErrorAccountRestricted = "connection.error.accountRestricted"
    case connectionErrorPasswordExpired = "connection.error.passwordExpired"
    case connectionErrorOther = "connection.error.other"
    case connectionErrorDetails = "connection.error.details"
    case certificateUnknownTitle = "certificate.unknown.title"
    case certificateChangedTitle = "certificate.changed.title"
    case certificateChangedWarning = "certificate.changed.warning"
    case certificateProblemUntrustedIssuer = "certificate.problem.untrustedIssuer"
    case certificateProblemNameMismatch = "certificate.problem.nameMismatch"
    case certificateProblemExpired = "certificate.problem.expired"
    case certificateProblemOther = "certificate.problem.other"
    case certificateDetails = "certificate.details"
    case certificateAdvice = "certificate.advice"
    case certificateRemember = "certificate.remember"
    case certificateActionConnect = "certificate.action.connect"
    case certificateActionConnectAnyway = "certificate.action.connectAnyway"
    case certificateActionCancel = "certificate.action.cancel"
}

extension TextKey {
    /// Base language, compiled in: the app speaks even without language files
    /// The switch is exhaustive, so a key without its base string does not compile
    var baseText: String {
        switch self {
        case .menuAppAbout: "О программе {app}"
        case .menuAppHide: "Скрыть {app}"
        case .menuAppHideOthers: "Скрыть остальные"
        case .menuAppShowAll: "Показать все"
        case .menuAppQuit: "Завершить {app}"
        case .menuFile: "Файл"
        case .menuFileDisconnect: "Отключиться"
        case .menuFileClose: "Закрыть окно"
        case .menuWindow: "Окно"
        case .menuWindowMinimize: "Свернуть"
        case .menuWindowFullScreen: "Во весь экран"
        case .connectionHostLabel: "Компьютер"
        case .connectionHostPlaceholder: "имя или адрес, порт — через двоеточие"
        case .connectionUserLabel: "Пользователь"
        case .connectionUserPlaceholder: "ДОМЕН\\пользователь или пользователь@домен"
        case .connectionPasswordLabel: "Пароль"
        case .connectionActionConnect: "Подключиться"
        case .connectionActionDisconnect: "Отключиться"
        case .connectionStatusInvalidHost: "Укажите компьютер: имя или адрес, порт — через двоеточие"
        case .connectionStatusConnecting: "Подключение к {host}…"
        case .connectionStatusConnected: "Подключено к {host}"
        case .connectionStatusDisconnected: "Отключено от {host}"
        case .connectionStatusStartFailed: "Не удалось начать подключение к {host}"
        case .connectionStatusNoMetal: "Этот Mac не может показать рабочий стол: нет доступа к Metal"
        case .connectionErrorHostNotFound: "Компьютер {host} не найден"
        case .connectionErrorUnreachable: "Компьютер {host} не принимает подключения"
        case .connectionErrorConnectionLost: "Соединение с {host} прервалось"
        case .connectionErrorSecurityFailed: "Не удалось установить защищённое соединение с {host}"
        case .connectionErrorCertificateRejected: "Подключение к {host} отменено: сертификат не принят"
        case .connectionErrorAuthentication: "Неверное имя пользователя или пароль"
        case .connectionErrorAccountRestricted: "Этой учётной записи запрещён вход на {host}"
        case .connectionErrorPasswordExpired: "Пароль нужно сменить"
        case .connectionErrorOther: "Не удалось подключиться к {host}"
        case .connectionErrorDetails: "{message} ({code})"
        case .certificateUnknownTitle: "Не удалось проверить подлинность {host}"
        case .certificateChangedTitle: "Сертификат {host} изменился"
        case .certificateChangedWarning: "Сервер предъявил не тот сертификат, что был запомнен. Так бывает после его замены — и при перехвате соединения."
        case .certificateProblemUntrustedIssuer: "Сертификат выдан центром, которому этот Mac не доверяет."
        case .certificateProblemNameMismatch: "Сертификат выдан на другое имя."
        case .certificateProblemExpired: "Срок действия сертификата истёк или ещё не начался."
        case .certificateProblemOther: "macOS не подтвердила сертификат (код {code})."
        case .certificateDetails: "Сертификат: {subject}\nSHA-256: {fingerprint}"
        case .certificateAdvice: "Подключайтесь, только если отпечаток совпадает с сертификатом сервера."
        case .certificateRemember: "Запомнить сертификат"
        case .certificateActionConnect: "Подключиться"
        case .certificateActionConnectAnyway: "Всё равно подключиться"
        case .certificateActionCancel: "Отмена"
        }
    }
}

enum Localization {
    /// The string of a key with its named placeholders filled in
    /// A placeholder without a value stays visible as {name}: a missing value shows up instead of vanishing
    static func text(_ key: TextKey, _ values: [String: String] = [:]) -> String {
        values.reduce(key.baseText) { text, value in
            text.replacingOccurrences(of: "{\(value.key)}", with: value.value)
        }
    }
}
