import os

/// Keys of the interface strings: flat and dotted, the same in every language
enum TextKey: String, CaseIterable {
    case menuAppAbout = "menu.app.about"
    case menuAppSettings = "menu.app.settings"
    case menuAppHide = "menu.app.hide"
    case menuAppHideOthers = "menu.app.hideOthers"
    case menuAppShowAll = "menu.app.showAll"
    case menuAppQuit = "menu.app.quit"
    case menuFile = "menu.file"
    case menuFileImport = "menu.file.import"
    case menuFileDisconnect = "menu.file.disconnect"
    case menuFileClose = "menu.file.close"
    case menuWindow = "menu.window"
    case menuWindowMinimize = "menu.window.minimize"
    case menuWindowFullScreen = "menu.window.fullScreen"
    case connectionHostLabel = "connection.host.label"
    case connectionHostPlaceholder = "connection.host.placeholder"
    case connectionUserLabel = "connection.user.label"
    case connectionUserPlaceholder = "connection.user.placeholder"
    case connectionPasswordLabel = "connection.password.label"
    case connectionActionConnect = "connection.action.connect"
    case connectionActionDisconnect = "connection.action.disconnect"
    case connectionStatusInvalidHost = "connection.status.invalidHost"
    case connectionStatusConnecting = "connection.status.connecting"
    case connectionStatusConnected = "connection.status.connected"
    case connectionStatusDisconnected = "connection.status.disconnected"
    case connectionStatusReconnecting = "connection.status.reconnecting"
    case connectionReconnectingAttempt = "connection.reconnecting.attempt"
    case connectionStatusStartFailed = "connection.status.startFailed"
    case connectionStatusNoMetal = "connection.status.noMetal"
    case connectionErrorHostNotFound = "connection.error.hostNotFound"
    case connectionErrorUnreachable = "connection.error.unreachable"
    case connectionErrorConnectionLost = "connection.error.connectionLost"
    case connectionErrorSecurityFailed = "connection.error.securityFailed"
    case connectionErrorCertificateRejected = "connection.error.certificateRejected"
    case connectionErrorAuthentication = "connection.error.authentication"
    case connectionErrorAccountRestricted = "connection.error.accountRestricted"
    case connectionErrorPasswordExpired = "connection.error.passwordExpired"
    case connectionErrorOther = "connection.error.other"
    case connectionErrorDetails = "connection.error.details"
    case certificateUnknownTitle = "certificate.unknown.title"
    case certificateChangedTitle = "certificate.changed.title"
    case certificateChangedWarning = "certificate.changed.warning"
    case certificateProblemUntrustedIssuer = "certificate.problem.untrustedIssuer"
    case certificateProblemNameMismatch = "certificate.problem.nameMismatch"
    case certificateProblemExpired = "certificate.problem.expired"
    case certificateProblemOther = "certificate.problem.other"
    case certificateDetails = "certificate.details"
    case certificateAdvice = "certificate.advice"
    case certificateRemember = "certificate.remember"
    case certificateActionConnect = "certificate.action.connect"
    case certificateActionConnectAnyway = "certificate.action.connectAnyway"
    case certificateActionCancel = "certificate.action.cancel"
    case settingsTitle = "settings.title"
    case settingsKeyboardTab = "settings.keyboard.tab"
    case settingsKeyboardModifiers = "settings.keyboard.modifiers"
    case settingsKeyboardLeftControl = "settings.keyboard.leftControl"
    case settingsKeyboardRightControl = "settings.keyboard.rightControl"
    case settingsKeyboardLeftOption = "settings.keyboard.leftOption"
    case settingsKeyboardRightOption = "settings.keyboard.rightOption"
    case settingsKeyboardLeftCommand = "settings.keyboard.leftCommand"
    case settingsKeyboardRightCommand = "settings.keyboard.rightCommand"
    case settingsKeyboardControl = "settings.keyboard.control"
    case settingsKeyboardAlt = "settings.keyboard.alt"
    case settingsKeyboardWindows = "settings.keyboard.windows"
    case settingsKeyboardPresetMac = "settings.keyboard.presetMac"
    case settingsKeyboardPresetPC = "settings.keyboard.presetPC"
    case settingsKeyboardIso = "settings.keyboard.iso"
    case settingsKeyboardIsoHint = "settings.keyboard.isoHint"
    case settingsKeyboardMacShortcuts = "settings.keyboard.macShortcuts"
    case settingsKeyboardMacShortcutsHint = "settings.keyboard.macShortcutsHint"
    case settingsKeyboardAdd = "settings.keyboard.add"
    case settingsKeyboardRemove = "settings.keyboard.remove"
    case settingsKeyboardDisconnect = "settings.keyboard.disconnect"
    case settingsKeyboardReset = "settings.keyboard.reset"
    case shortcutNone = "shortcut.none"
    case shortcutRecording = "shortcut.recording"
    case shortcutHint = "shortcut.hint"
    case connectionsNewName = "connections.newName"
    case connectionsUntitled = "connections.untitled"
    case connectionsAdd = "connections.add"
    case connectionsRemove = "connections.remove"
    case connectionsEmptyTitle = "connections.empty.title"
    case connectionsEmptyMessage = "connections.empty.message"
    case profileNameLabel = "profile.name.label"
    case profileNamePlaceholder = "profile.name.placeholder"
    case profilePasswordAskPlaceholder = "profile.password.askPlaceholder"
    case profilePasswordSavedPlaceholder = "profile.password.savedPlaceholder"
    case profilePasswordRemember = "profile.password.remember"
    case profilePasswordForget = "profile.password.forget"
    case profileKeyboardSection = "profile.keyboard.section"
    case profileKeyboardLabel = "profile.keyboard.label"
    case profileKeyboardSettings = "profile.keyboard.settings"
    case credentialsTitleServer = "credentials.title.server"
    case credentialsTitleGateway = "credentials.title.gateway"
    case credentialsMessageAsk = "credentials.message.ask"
    case credentialsMessageRetry = "credentials.message.retry"
    case credentialsActionSignIn = "credentials.action.signIn"
    case credentialsActionCancel = "credentials.action.cancel"
    case connectionPasswordNotSaved = "connection.password.notSaved"
    case connectionPasswordLabelInKeychain = "connection.password.labelInKeychain"
    case connectionsImported = "connections.imported"
    case connectionsImportedExisting = "connections.importedExisting"
    case connectionsImportFailed = "connections.importFailed"
    case profileGatewaySection = "profile.gateway.section"
    case profileGatewayAddressLabel = "profile.gateway.address.label"
    case profileGatewayAddressPlaceholder = "profile.gateway.address.placeholder"
    case profileGatewaySameCredentials = "profile.gateway.sameCredentials"
    case profileGatewayUserLabel = "profile.gateway.user.label"
    case profileGatewayBypassLocal = "profile.gateway.bypassLocal"
    case connectionStatusInvalidGateway = "connection.status.invalidGateway"
    case connectionErrorGatewayDenied = "connection.error.gatewayDenied"
    case gatewayMessageTitle = "gateway.message.title"
    case gatewayMessageAccept = "gateway.message.accept"
    case gatewayMessageDecline = "gateway.message.decline"
    case gatewayMessageClose = "gateway.message.close"
    case connectionGatewayPasswordLabelInKeychain = "connection.gatewayPassword.labelInKeychain"
    case languageBaseName = "language.base.name"
    case settingsLanguageTab = "settings.language.tab"
    case settingsLanguageLabel = "settings.language.label"
    case settingsLanguageSystem = "settings.language.system"
    case settingsLanguageRestart = "settings.language.restart"
    case settingsLanguageFolderHint = "settings.language.folderHint"
    case settingsLanguageOpenFolder = "settings.language.openFolder"
    case settingsLanguageCreateBase = "settings.language.createBase"
    case settingsLanguageCreateBaseFailed = "settings.language.createBaseFailed"
    case clipboardFilesCopying = "clipboard.files.copying"
    case clipboardFilesProgress = "clipboard.files.progress"
    case clipboardFilesCancel = "clipboard.files.cancel"
    case clipboardFilesFailed = "clipboard.files.failed"
}

extension TextKey {
    /// Base language, compiled in: the app speaks even without language files
    /// The switch is exhaustive, so a key without its base string does not compile
    var baseText: String {
        switch self {
        case .menuAppAbout: "О программе {app}"
        case .menuAppSettings: "Настройки…"
        case .menuAppHide: "Скрыть {app}"
        case .menuAppHideOthers: "Скрыть остальные"
        case .menuAppShowAll: "Показать все"
        case .menuAppQuit: "Завершить {app}"
        case .menuFile: "Файл"
        case .menuFileImport: "Импортировать файл .rdp…"
        case .menuFileDisconnect: "Отключиться"
        case .menuFileClose: "Закрыть окно"
        case .menuWindow: "Окно"
        case .menuWindowMinimize: "Свернуть"
        case .menuWindowFullScreen: "Во весь экран"
        case .connectionHostLabel: "Компьютер"
        case .connectionHostPlaceholder: "имя или адрес, порт — через двоеточие"
        case .connectionUserLabel: "Пользователь"
        case .connectionUserPlaceholder: "ДОМЕН\\пользователь или пользователь@домен"
        case .connectionPasswordLabel: "Пароль"
        case .connectionActionConnect: "Подключиться"
        case .connectionActionDisconnect: "Отключиться"
        case .connectionStatusInvalidHost: "Укажите компьютер: имя или адрес, порт — через двоеточие"
        case .connectionStatusConnecting: "Подключение к {host}…"
        case .connectionStatusConnected: "Подключено к {host}"
        case .connectionStatusDisconnected: "Отключено от {host}"
        case .connectionStatusReconnecting: "Связь с {host} прервалась — переподключение…"
        case .connectionReconnectingAttempt: "Попытка {attempt} из {count}"
        case .connectionStatusStartFailed: "Не удалось начать подключение к {host}"
        case .connectionStatusNoMetal: "Этот Mac не может показать рабочий стол: нет доступа к Metal"
        case .connectionErrorHostNotFound: "Компьютер {host} не найден"
        case .connectionErrorUnreachable: "Компьютер {host} не принимает подключения"
        case .connectionErrorConnectionLost: "Соединение с {host} прервалось"
        case .connectionErrorSecurityFailed: "Не удалось установить защищённое соединение с {host}"
        case .connectionErrorCertificateRejected: "Подключение к {host} отменено: сертификат не принят"
        case .connectionErrorAuthentication: "Неверное имя пользователя или пароль"
        case .connectionErrorAccountRestricted: "Этой учётной записи запрещён вход на {host}"
        case .connectionErrorPasswordExpired: "Пароль нужно сменить"
        case .connectionErrorOther: "Не удалось подключиться к {host}"
        case .connectionErrorDetails: "{message} ({code})"
        case .certificateUnknownTitle: "Не удалось проверить подлинность {host}"
        case .certificateChangedTitle: "Сертификат {host} изменился"
        case .certificateChangedWarning: "Сервер предъявил не тот сертификат, что был запомнен. Так бывает после его замены — и при перехвате соединения."
        case .certificateProblemUntrustedIssuer: "Сертификат выдан центром, которому этот Mac не доверяет."
        case .certificateProblemNameMismatch: "Сертификат выдан на другое имя."
        case .certificateProblemExpired: "Срок действия сертификата истёк или ещё не начался."
        case .certificateProblemOther: "macOS не подтвердила сертификат (код {code})."
        case .certificateDetails: "Сертификат: {subject}\nSHA-256: {fingerprint}"
        case .certificateAdvice: "Подключайтесь, только если отпечаток совпадает с сертификатом сервера."
        case .certificateRemember: "Запомнить сертификат"
        case .certificateActionConnect: "Подключиться"
        case .certificateActionConnectAnyway: "Всё равно подключиться"
        case .certificateActionCancel: "Отмена"
        case .settingsTitle: "Настройки"
        case .settingsKeyboardTab: "Клавиатура"
        case .settingsKeyboardModifiers: "Клавиши Мака в Windows"
        case .settingsKeyboardLeftControl: "Левая ⌃ Control"
        case .settingsKeyboardRightControl: "Правая ⌃ Control"
        case .settingsKeyboardLeftOption: "Левая ⌥ Option"
        case .settingsKeyboardRightOption: "Правая ⌥ Option"
        case .settingsKeyboardLeftCommand: "Левая ⌘ Command"
        case .settingsKeyboardRightCommand: "Правая ⌘ Command"
        case .settingsKeyboardControl: "Ctrl"
        case .settingsKeyboardAlt: "Alt"
        case .settingsKeyboardWindows: "Windows"
        case .settingsKeyboardPresetMac: "Как на Маке"
        case .settingsKeyboardPresetPC: "Как на PC"
        case .settingsKeyboardIso: "Между левым Shift и Z есть ещё одна клавиша"
        case .settingsKeyboardIsoHint:
            "Так устроены клавиатуры ISO: у них macOS путает эту клавишу с клавишей слева от 1."
        case .settingsKeyboardMacShortcuts: "Сочетания, которые остаются Маку"
        case .settingsKeyboardMacShortcutsHint:
            "Пока рабочий стол принимает клавиатуру, все остальные сочетания получает Windows."
        case .settingsKeyboardAdd: "Добавить…"
        case .settingsKeyboardRemove: "Удалить"
        case .settingsKeyboardDisconnect: "Отключиться"
        case .settingsKeyboardReset: "Вернуть по умолчанию"
        case .shortcutNone: "Нет"
        case .shortcutRecording: "Нажмите сочетание"
        case .shortcutHint: "Сочетание — с ⌘, ⌃, ⌥ или fn. ⎋ — отмена, ⌫ — без сочетания."
        case .connectionsNewName: "Новое подключение"
        case .connectionsUntitled: "Без названия"
        case .connectionsAdd: "Добавить подключение"
        case .connectionsRemove: "Удалить подключение"
        case .connectionsEmptyTitle: "Нет подключений"
        case .connectionsEmptyMessage: "Добавьте компьютер Windows, к которому будете подключаться."
        case .profileNameLabel: "Название"
        case .profileNamePlaceholder: "как показывать в списке"
        case .profilePasswordAskPlaceholder: "спросить при подключении"
        case .profilePasswordSavedPlaceholder: "сохранён в связке ключей"
        case .profilePasswordRemember: "Запомнить пароль в связке ключей"
        case .profilePasswordForget: "Забыть сохранённые пароли"
        case .profileKeyboardSection: "Клавиатура"
        case .profileKeyboardLabel: "Клавиши-модификаторы"
        case .profileKeyboardSettings: "Как в настройках"
        case .credentialsTitleServer: "Вход на {host}"
        case .credentialsTitleGateway: "Вход на шлюз {host}"
        case .credentialsMessageAsk: "Введите имя пользователя и пароль."
        case .credentialsMessageRetry: "Неверное имя пользователя или пароль. Попробуйте ещё раз."
        case .credentialsActionSignIn: "Войти"
        case .credentialsActionCancel: "Отмена"
        case .connectionPasswordNotSaved: "Пароль не сохранён: связка ключей ответила кодом {code}"
        case .connectionPasswordLabelInKeychain: "VibeRDP: {connection}"
        case .connectionsImported: "Подключение «{name}» добавлено из файла"
        case .connectionsImportedExisting: "Подключение «{name}» уже есть в списке"
        case .connectionsImportFailed: "{file} — не файл подключения к удалённому рабочему столу"
        case .profileGatewaySection: "Шлюз удалённых рабочих столов"
        case .profileGatewayAddressLabel: "Шлюз"
        case .profileGatewayAddressPlaceholder: "пусто — подключаться напрямую"
        case .profileGatewaySameCredentials: "Те же имя и пароль, что у компьютера"
        case .profileGatewayUserLabel: "Пользователь шлюза"
        case .profileGatewayBypassLocal: "Напрямую, если компьютер в локальной сети"
        case .connectionStatusInvalidGateway: "Укажите шлюз: имя или адрес, порт — через двоеточие"
        case .connectionErrorGatewayDenied:
            "Шлюз {gateway} не пустил: неверное имя или пароль, либо нет права подключаться через него"
        case .gatewayMessageTitle: "Сообщение шлюза {gateway}"
        case .gatewayMessageAccept: "Принять"
        case .gatewayMessageDecline: "Отклонить"
        case .gatewayMessageClose: "Закрыть"
        case .connectionGatewayPasswordLabelInKeychain: "VibeRDP, шлюз: {connection}"
        case .languageBaseName: "Русский"
        case .settingsLanguageTab: "Язык"
        case .settingsLanguageLabel: "Язык интерфейса"
        case .settingsLanguageSystem: "Как в системе"
        case .settingsLanguageRestart: "Другой язык заговорит после перезапуска VibeRDP."
        case .settingsLanguageFolderHint:
            "Языки — файлы в папке {folder}: положите туда перевод, и он появится в списке после перезапуска."
        case .settingsLanguageOpenFolder: "Открыть папку языков"
        case .settingsLanguageCreateBase: "Создать файл для правки"
        case .settingsLanguageCreateBaseFailed: "Файл не создан: {reason}"
        case .clipboardFilesCopying: "Копирование файлов с удалённого компьютера"
        case .clipboardFilesProgress: "{done} из {total}"
        case .clipboardFilesCancel: "Отменить"
        case .clipboardFilesFailed:
            "Файлы не скопированы: удалённый компьютер их не отдал, или их не удалось записать на Мак"
        }
    }
}

enum Localization {
    /// The strings of the language this launch speaks, over the base ones; set once, before the first window
    private static let strings = OSAllocatedUnfairLock(initialState: [String: String]())

    /// The catalog of this launch, from Languages: the base keeps every key a language does not translate
    static func use(_ catalog: [String: String]) {
        strings.withLock { $0 = catalog }
    }

    /// The string of a key with its named placeholders filled in
    /// A placeholder without a value stays visible as {name}: a missing value shows up instead of vanishing
    static func text(_ key: TextKey, _ values: [String: String] = [:]) -> String {
        let template = strings.withLock { $0[key.rawValue] } ?? key.baseText
        return fill(template, values)
    }

    static func fill(_ template: String, _ values: [String: String]) -> String {
        values.reduce(template) { text, value in
            text.replacingOccurrences(of: "{\(value.key)}", with: value.value)
        }
    }
}
